export const DEFAULT_SITE_SETTINGS = {
  store_name: 'شركة الرحمة لتشكيل المعادن',
  default_language: 'ar',

  hero_badge: 'جودة للخامات، سعر مميز، سرعة تسليم',
  hero_title: 'شركة الرحمة لتشكيل المعادن',
  hero_desc: 'جودة للخامات، سعر مميز، سرعة تسليم',
  hero_image: '/rahma/earth-rods.png',
  hero_image_2: '/rahma/grounding-clamp.png',
  hero_image_3: '/rahma/copper-busbar.png',

  ticker_text_1: 'شهادات ضمان',
  ticker_text_2: 'منتجات معتمدة',
  ticker_text_3: 'عملاء وثقوا بنا',
  ticker_text_4: 'سرعة في التسليم',

  about_subtitle: 'نبذة عن شركتنا',
  about_title: 'شركة الرحمة لتشكيل المعادن',
  about_text: 'نعد شركة الرحمة لتشكيل المعادن واحدة من الشركات المتخصصة في تشكيل وتشغيل المعادن في السوق المصري، ونقدم حلولاً معدنية متكاملة تشمل تشكيل وتصنيع مختلف المواد المعدنية. نمتلك خبرة عالية ومهارة دقيقة لتلبية احتياجات العملاء الصناعية والتجارية، مع الالتزام بتقديم خامات ومنتجات عالية الجودة وخدمات متكاملة في مجالات الحديد والنحاس ومعالجة المعادن.',
  about_image: '/rahma/copper-busbar.png',

  why_subtitle: 'الميزة الصناعية',
  why_title: 'أهدافنا',
  why_desc: 'تسعى شركة الرحمة لتشكيل المعادن إلى توفير منتجات معدنية عالية الجودة تلبي احتياجات السوق المصرية والمشروعات الصناعية والإنشائية، مع الالتزام بأعلى معايير السلامة والجودة في صناعة وتشغيل المعادن.',
  feature_title_1: 'تصنيع دقيق',
  feature_desc_1: 'معدات حديثة ومعايير صارمة لكل قطعة يتم تشكيلها وتجهيزها.',
  feature_title_2: 'جودة الخامات',
  feature_desc_2: 'نحاس معتمد ومكونات مختارة لمقاومة التآكل والعمل الطويل.',
  feature_title_3: 'حلول حسب المشروع',
  feature_desc_3: 'توريد وتجهيز يناسب متطلبات المصانع والمباني والبنية التحتية.',
  feature_title_4: 'توريد موثوق',
  feature_desc_4: 'التزام بالمواعيد وتجهيز كميات مناسبة للمشروعات المتوسطة والكبيرة.',
  feature_title_5: 'دعم فني',
  feature_desc_5: 'مساندة فنية قبل التوريد وبعده لاختيار القطع الأنسب للتطبيق.',

  footer_locations: '[]',
  facebook_link: '',
  instagram_link: '',
  tiktok_link: '',
  support_whatsapp: '01158737530',
  admin_whatsapp: '01123539739',
  contact_phone_3: '01040959500',
  contact_email: 'info@elrahmametalforming.com',
  contact_address: 'وسط البلد، القاهرة، مصر',

  rahma_brand_subtitle: 'لتشكيل المعادن',
  rahma_quote_button: 'اطلب عرض سعر',
  rahma_hero_primary_cta: 'استكشف منتجاتنا',
  rahma_hero_secondary_cta: 'اطلب استشارة فنية',
  rahma_trust_1: 'جودة تصنيع عالية',
  rahma_trust_2: 'خامات نحاس معتمدة',
  rahma_trust_3: 'حلول للمشروعات والمنشآت',
  rahma_flow_title: 'منظومة تأريض متكاملة',
  rahma_flow_subtitle: 'من مانع الصواعق إلى باطن الأرض، كل مكون في مكانه الصحيح.',
  rahma_categories_title: 'منتجات شركة الرحمة لتشكيل المعادن',
  rahma_categories_subtitle: 'خامات ومكونات معدنية متخصصة بجودة عالية وسرعة تجهيز للمشروعات.',
  rahma_categories_button: 'عرض كل المنتجات',
  rahma_categories_enabled: 'true',
  rahma_featured_title: 'منتجات مميزة',
  rahma_featured_subtitle: 'اختيارات مناسبة للمشروعات والتوريد الصناعي بمواصفات واضحة.',
  rahma_featured_button: 'استعرض المنتجات',
  rahma_featured_enabled: 'true',
  rahma_sectors_title: 'قطاعات نخدمها',
  rahma_sectors_subtitle: 'خبرة واسعة في تجهيز المشروعات الكبرى والصغرى بقطع تأريض وحماية موثوقة.',
  rahma_sectors_button: 'اذهب إلى المنتجات',
  rahma_sectors_enabled: 'true',
  rahma_sector_1_title: 'المصانع',
  rahma_sector_1_desc: 'منظومات تأريض ضخمة للمنشآت الصناعية وخطوط الإنتاج.',
  rahma_sector_1_image: '/rahma/copper-busbar.png',
  rahma_sector_2_title: 'المجمعات السكنية',
  rahma_sector_2_desc: 'حلول تأريض وحماية للمباني السكنية متعددة الطوابق.',
  rahma_sector_2_image: '/rahma/earth-pit.png',
  rahma_sector_3_title: 'المباني التجارية',
  rahma_sector_3_desc: 'أنظمة تأريض للمولات والأبراج والمكاتب التجارية.',
  rahma_sector_3_image: '/rahma/grounding-clamp.png',
  rahma_sector_4_title: 'البنية التحتية',
  rahma_sector_4_desc: 'محطات كهرباء ومضخات ومشروعات حيوية تحتاج موثوقية عالية.',
  rahma_sector_4_image: '/rahma/lightning-base.png',
  rahma_sector_5_title: 'المواقع الصناعية',
  rahma_sector_5_desc: 'مصافي ومنشآت بتروكيماوية ومستودعات ومشروعات خاصة.',
  rahma_sector_5_image: '/rahma/copper-lugs.png',
  rahma_cta_title: 'يوجد لدينا شحن لجميع المحافظات',
  rahma_cta_subtitle: 'نوفر توريداً منظماً وسريعاً لمنتجات شركة الرحمة في جميع أنحاء الجمهورية.',
  rahma_cta_button: 'اتصل بنا',

  booking_price_per_tray: '120',
  booking_trays_per_qirat: '6',
  booking_notes: 'سيتم التواصل معك لتأكيد تفاصيل التوريد والتسليم.',
  booking_gallery_images: '[]',
  booking_seo_image_1: '',
  booking_seo_image_2: '',
  booking_seo_image_3: '',
  booking_seo_image_4: '',
  booking_seo_image_5: ''
};
