# Generated by Django 5.2.15 on 2026-06-12 19:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ar', models.CharField(max_length=120)),
                ('name_en', models.CharField(blank=True, max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('title_ar', models.CharField(blank=True, max_length=140)),
                ('title_en', models.CharField(blank=True, max_length=140)),
                ('bio_ar', models.TextField(blank=True, max_length=1200)),
                ('bio_en', models.TextField(blank=True, max_length=1200)),
                ('avatar', models.ImageField(blank=True, upload_to=news.models.news_asset_upload_to)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ('name_ar',),
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('source', models.CharField(default='sc_news', max_length=80)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='NewsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ar', models.CharField(max_length=80)),
                ('name_en', models.CharField(blank=True, max_length=80)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('name_ar',),
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ar', models.CharField(max_length=120)),
                ('name_en', models.CharField(blank=True, max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description_ar', models.TextField(blank=True, max_length=700)),
                ('description_en', models.TextField(blank=True, max_length=700)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='published', max_length=16)),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name_plural': 'News categories',
                'ordering': ('sort_order', 'name_ar'),
                'indexes': [models.Index(fields=['status', 'sort_order'], name='news_cat_status_sort_idx')],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_ar', models.CharField(max_length=220)),
                ('title_en', models.CharField(blank=True, max_length=220)),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('excerpt_ar', models.TextField(max_length=600)),
                ('excerpt_en', models.TextField(blank=True, max_length=600)),
                ('body_ar', models.TextField()),
                ('body_en', models.TextField(blank=True)),
                ('featured_image', models.ImageField(blank=True, upload_to=news.models.news_asset_upload_to)),
                ('image_alt_ar', models.CharField(blank=True, max_length=180)),
                ('image_alt_en', models.CharField(blank=True, max_length=180)),
                ('article_type', models.CharField(choices=[('news', 'News'), ('company_update', 'Company update'), ('guide', 'Guide'), ('video', 'Video'), ('case_study', 'Case study')], db_index=True, default='news', max_length=24)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_breaking', models.BooleanField(db_index=True, default=False)),
                ('is_trending', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('read_time_minutes', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)])),
                ('views_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('meta_title_ar', models.CharField(blank=True, max_length=180)),
                ('meta_title_en', models.CharField(blank=True, max_length=180)),
                ('meta_description_ar', models.CharField(blank=True, max_length=220)),
                ('meta_description_en', models.CharField(blank=True, max_length=220)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.newsauthor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='news.newscategory')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='news.newstag')),
            ],
            options={
                'ordering': ('-published_at', '-created_at'),
                'indexes': [models.Index(fields=['status', '-published_at'], name='news_article_status_pub_idx'), models.Index(fields=['article_type', 'status', '-published_at'], name='news_article_type_status_idx'), models.Index(fields=['category', 'status', '-published_at'], name='news_article_cat_status_idx'), models.Index(fields=['is_featured', 'status', '-published_at'], name='news_article_featured_idx'), models.Index(fields=['is_breaking', 'status', '-published_at'], name='news_article_breaking_idx'), models.Index(fields=['is_trending', 'status', '-published_at'], name='news_article_trending_idx')],
            },
        ),
    ]
