import {
  PortfolioProjectLink,
  PortfolioServiceNode,
  PortfolioTeamNode,
} from './types';

const ACCENTS = {
  plum: '#6d3355',
  magenta: '#9d027c',
  gold: '#d4a24c',
  amber: '#c98534',
  rose: '#b45d76',
  slate: '#556274',
  teal: '#5c7b78',
  ink: '#211c24',
} as const;

const createNode = (
  node: Omit<PortfolioTeamNode, 'imagePng'> & { imagePng?: string }
): PortfolioTeamNode => ({
  imagePng: '',
  accent: ACCENTS.plum,
  projectTags: [],
  ...node,
});

export const portfolioPageCopy = {
  ar: {
    badge: 'طريقة عمل واضحة من الفكرة حتى التسليم',
    title: 'مشروعاتنا ليست لقطات جميلة فقط، بل نتائج يمكن فهمها وتتبعها.',
    subtitle:
      'استعرض كيف تتكامل الهوية، الموقع، المحتوى، والإنتاج داخل مشروع واحد يخدم هدفاً تجارياً واضحاً: ظهور أفضل، ثقة أعلى، وطلبات أكثر تنظيماً.',
    legendTitle: 'مستويات الشبكة',
    rings: {
      0: 'CEO',
      1: 'القيادة الأقرب',
      2: 'مديرو المسارات',
      3: 'فرق التنفيذ',
    },
    panelTitle: 'نقطة التركيز',
    panelLead:
      'مرر على أي نقطة لترى دورها في التنفيذ وكيف ترتبط بالمخرجات النهائية للمشروع.',
    departmentLabel: 'القسم',
    projectsLabel: 'المشروعات المرتبطة',
    noProjects: 'يتقاطع مع أكثر من مسار داخلي داخل الشركة.',
    teamStat: 'عنصر داخل الشبكة',
    orbitStat: 'دوائر تشغيل',
    focusHint: 'على الهاتف: اضغط على أي عنصر لإظهار البطاقة التفصيلية.',
    placeholderPortrait: 'صورة الفريق النهائية تُستبدل هنا',
    browseTitle: 'تصفح مشروعاتنا',
    browseLead:
      'الروابط الحية تفتح الأعمال الجاهزة الآن، والمسارات التالية توضّح أنواع المشاريع التي نجهزها داخل منظومة الخدمات.',
    liveLabel: 'Live',
    soonLabel: 'Coming Soon',
    openAction: 'فتح الصفحة',
    soonAction: 'قريبًا',
    servicesTitle: 'شبكة الخدمات',
    servicesLead:
      'كل خدمة تكمل الأخرى: الهوية ترفع الثقة، الموقع يحول الطلب، المحتوى يجذب الانتباه، والمتابعة تقيس التحسن.',
  },
  en: {
    badge: 'A clear working method from idea to delivery',
    title: 'Our projects are not just polished visuals. They are outcomes you can understand and track.',
    subtitle:
      'See how identity, websites, content, and production come together around one business goal: stronger visibility, higher trust, and more organized requests.',
    legendTitle: 'Network tiers',
    rings: {
      0: 'CEO',
      1: 'Core leadership',
      2: 'Track leads',
      3: 'Delivery teams',
    },
    panelTitle: 'Focus panel',
    panelLead:
      'Hover or focus any point to see its role in execution and how it connects to the final project output.',
    departmentLabel: 'Department',
    projectsLabel: 'Project scope',
    noProjects: 'Supports multiple internal delivery tracks.',
    teamStat: 'nodes in motion',
    orbitStat: 'delivery rings',
    focusHint: 'On mobile: tap any person to open the detail sheet.',
    placeholderPortrait: 'Final team portrait swaps in here',
    browseTitle: 'Browse Our Projects',
    browseLead:
      'Live links open ready work today, while upcoming tracks show the types of projects being prepared across the service system.',
    liveLabel: 'Live',
    soonLabel: 'Coming Soon',
    openAction: 'Open page',
    soonAction: 'Soon',
    servicesTitle: 'Service Network',
    servicesLead:
      'Each service strengthens the next: identity builds trust, the website converts, content earns attention, and follow-up measures improvement.',
  },
} as const;

export const portfolioProjectLinks: PortfolioProjectLink[] = [
  {
    id: 'branding',
    titleAr: 'الهوية البصرية',
    titleEn: 'Brand Identity',
    href: '/branding',
    status: 'live',
    icon: 'Palette',
    accent: ACCENTS.magenta,
    eyebrowAr: 'Brand Systems',
    eyebrowEn: 'Brand Systems',
    summaryAr: 'عرض الهويات، الأنظمة البصرية، وتكوين لغة العلامة على الشاشات والمواد.',
    summaryEn: 'Identity systems, visual language, and brand applications across screens and materials.',
    planStepsAr: ['تحليل العلامة', 'دراسة الجمهور', 'مراجعة المنافسين', 'شخصية البراند', 'لوحة الألوان', 'اختيار الخطوط', 'تطوير الشعار', 'تطبيقات الهوية', 'قوالب العرض', 'دليل الهوية', 'مراجعة الجودة', 'ملفات التسليم'],
    planStepsEn: ['Brand analysis', 'Audience study', 'Competitor review', 'Brand personality', 'Color palette', 'Typography', 'Logo system', 'Identity applications', 'Presentation templates', 'Brand guide', 'Quality review', 'Delivery files'],
    orbit: 0,
    previewType: 'identity',
    signalLabel: 'Branding',
    routeTab: 'branding',
  },
  {
    id: 'websites',
    titleAr: 'المواقع والمنصات',
    titleEn: 'Websites & Portals',
    href: '/websites',
    status: 'live',
    icon: 'Globe',
    accent: ACCENTS.gold,
    eyebrowAr: 'Digital Experiences',
    eyebrowEn: 'Digital Experiences',
    summaryAr: 'مشروعات المواقع والواجهات التي تجمع السرعة، التحويل، والتفصيل التقني.',
    summaryEn: 'Website projects that combine speed, conversion, and technical craft.',
    planStepsAr: ['دراسة الهدف', 'خريطة الصفحات', 'تجربة المستخدم', 'تصميم الواجهة', 'نسخة الموبايل', 'تطوير الواجهة', 'الربط الخلفي', 'تحسين السرعة', 'نماذج التواصل', 'اختبار الجودة', 'إطلاق الموقع', 'متابعة الأداء'],
    planStepsEn: ['Goal study', 'Page map', 'User experience', 'Interface design', 'Mobile version', 'Frontend build', 'Backend links', 'Speed tuning', 'Contact forms', 'Quality testing', 'Website launch', 'Performance follow-up'],
    orbit: 60,
    previewType: 'website',
    signalLabel: 'Web',
    routeTab: 'projects-websites',
  },
  {
    id: 'social',
    titleAr: 'السوشيال ميديا',
    titleEn: 'Social Media',
    href: '/social-media',
    status: 'live',
    icon: 'Share2',
    accent: ACCENTS.amber,
    eyebrowAr: 'Campaign Outputs',
    eyebrowEn: 'Campaign Outputs',
    summaryAr: 'نماذج الحملات والتصميمات اليومية ومسارات التواصل التي تدعم الأداء.',
    summaryEn: 'Campaign outputs, daily design systems, and communication tracks that support performance.',
    planStepsAr: ['تحديد الحملة', 'تحليل الجمهور', 'رسائل الحملة', 'تقويم المحتوى', 'أفكار المنشورات', 'تصميم القوالب', 'كتابة النصوص', 'تجهيز الإعلانات', 'جدولة النشر', 'متابعة التفاعل', 'قياس الأداء', 'تحسين الحملة'],
    planStepsEn: ['Campaign direction', 'Audience analysis', 'Campaign messages', 'Content calendar', 'Post ideas', 'Template design', 'Copywriting', 'Ad setup', 'Publishing schedule', 'Engagement tracking', 'Performance review', 'Campaign optimization'],
    orbit: 120,
    previewType: 'social',
    signalLabel: 'Social',
    routeTab: 'projects-social',
  },
  {
    id: 'animation',
    titleAr: 'فيديوهات الرسوم المتحركة',
    titleEn: 'Animated Videos',
    href: '/animation',
    status: 'soon',
    icon: 'Video',
    accent: ACCENTS.rose,
    eyebrowAr: 'Motion Systems',
    eyebrowEn: 'Motion Systems',
    summaryAr: 'مسار مخصص للموشن والتوضيح البصري قيد الإضافة للمنظومة.',
    summaryEn: 'A dedicated motion and explainer track is being added to the portfolio.',
    planStepsAr: ['كتابة السكريبت', 'تقسيم المشاهد', 'ستوري بورد', 'تصميم الشخصيات', 'تصميم الخلفيات', 'تسجيل الصوت', 'تحريك أولي', 'تحريك نهائي', 'المؤثرات', 'المونتاج', 'التصدير', 'نسخة التسليم'],
    planStepsEn: ['Script writing', 'Scene breakdown', 'Storyboard', 'Character design', 'Background design', 'Voice recording', 'Rough animation', 'Final animation', 'Effects', 'Editing', 'Export', 'Delivery version'],
    orbit: 180,
    previewType: 'motion',
    signalLabel: 'Motion',
    routeTab: 'projects-animation',
  },
  {
    id: 'promotional',
    titleAr: 'الفيديوهات الدعائية',
    titleEn: 'Promotional Films',
    href: '/promotional',
    status: 'live',
    icon: 'Film',
    accent: ACCENTS.plum,
    eyebrowAr: 'Production Lane',
    eyebrowEn: 'Production Lane',
    summaryAr: 'مشروعات الإنتاج المصور والإخراج الدعائي ستظهر هنا قريبًا.',
    summaryEn: 'Filmed promotional production work will land here soon.',
    planStepsAr: ['فكرة الإعلان', 'هدف الفيديو', 'كتابة السيناريو', 'خطة التصوير', 'تجهيز الموقع', 'ضبط الإضاءة', 'التصوير', 'اختيار اللقطات', 'المونتاج', 'تصحيح الألوان', 'نسخ نهائية', 'التسليم'],
    planStepsEn: ['Ad concept', 'Video objective', 'Scenario writing', 'Shoot plan', 'Location setup', 'Lighting setup', 'Filming', 'Shot selection', 'Editing', 'Color correction', 'Final versions', 'Delivery'],
    orbit: 240,
    previewType: 'video',
    signalLabel: 'Film',
    routeTab: 'projects-promotional',
  },
  {
    id: 'photography',
    titleAr: 'التصوير الفوتوغرافي',
    titleEn: 'Product Photography',
    href: '/photography',
    status: 'soon',
    icon: 'Camera',
    accent: ACCENTS.teal,
    eyebrowAr: 'Studio Capture',
    eyebrowEn: 'Studio Capture',
    summaryAr: 'مسار التصوير والستوديو قيد الترتيب ليكتمل عرض الخدمات البصرية.',
    summaryEn: 'The photography and studio lane is being prepared to complete the visual service map.',
    planStepsAr: ['تحضير المنتج', 'تنسيق المشهد', 'ضبط الإضاءة', 'اختيار العدسة', 'زوايا التصوير', 'لقطات التفاصيل', 'خلفيات بديلة', 'مراجعة الصور', 'اختيار الأفضل', 'المعالجة', 'تصدير المقاسات', 'تسليم الصور'],
    planStepsEn: ['Product prep', 'Scene styling', 'Lighting setup', 'Lens choice', 'Shooting angles', 'Detail shots', 'Alt backgrounds', 'Photo review', 'Best selection', 'Retouching', 'Size exports', 'Photo delivery'],
    orbit: 300,
    previewType: 'camera',
    signalLabel: 'Studio',
    routeTab: 'projects-photography',
  },
];

export const portfolioServiceNodes: PortfolioServiceNode[] = [
  // SOFTWARE
  {
    id: 'sw-web',
    titleAr: 'موقع شركة',
    titleEn: 'Corporate Website',
    summaryAr: 'بناء الحضور الرقمي للشركات.',
    summaryEn: 'Building corporate digital presence.',
    accent: ACCENTS.slate,
    icon: 'Globe',
    href: '/software?service=web#software-systems',
    group: 'software'
  },
  {
    id: 'sw-commerce',
    titleAr: 'متجر إلكتروني',
    titleEn: 'E-commerce',
    summaryAr: 'منصات بيع إلكترونية متكاملة.',
    summaryEn: 'Integrated e-commerce platforms.',
    accent: ACCENTS.slate,
    icon: 'ShoppingCart',
    href: '/software?service=commerce#software-systems',
    group: 'software'
  },
  {
    id: 'sw-crm',
    titleAr: 'CRM',
    titleEn: 'CRM',
    summaryAr: 'أنظمة إدارة علاقات العملاء.',
    summaryEn: 'Customer relationship management systems.',
    accent: ACCENTS.slate,
    icon: 'Users',
    href: '/software?service=crm#software-systems',
    group: 'software'
  },
  {
    id: 'sw-ai',
    titleAr: 'مساعد ذكي',
    titleEn: 'AI Assistant',
    summaryAr: 'مساعدون أذكياء لخدمة العملاء.',
    summaryEn: 'Smart assistants for customer service.',
    accent: ACCENTS.slate,
    icon: 'Bot',
    href: '/software?service=ai#software-systems',
    group: 'software'
  },
  {
    id: 'sw-auto',
    titleAr: 'أتمتة',
    titleEn: 'Automation',
    summaryAr: 'أتمتة العمليات اليومية للشركات.',
    summaryEn: 'Automating daily business operations.',
    accent: ACCENTS.slate,
    icon: 'Zap',
    href: '/software?service=automation#software-systems',
    group: 'software'
  },
  {
    id: 'sw-growth',
    titleAr: 'تطوير موقعك',
    titleEn: 'Website Growth',
    summaryAr: 'تطوير وتوسيع نطاق المنصات الحالية.',
    summaryEn: 'Developing and scaling existing platforms.',
    accent: ACCENTS.slate,
    icon: 'TrendingUp',
    href: '/software?service=growth#software-systems',
    group: 'software'
  },

  // GROWTH & BRANDING
  {
    id: 'gb-management',
    titleAr: 'خطط الإدارة',
    titleEn: 'Management Plans',
    summaryAr: 'إدارة المحتوى والصفحات باحترافية.',
    summaryEn: 'Professional content and page management.',
    accent: ACCENTS.amber,
    icon: 'LayoutDashboard',
    href: '/social?planType=marketing#marketing-plans-row',
    group: 'growth'
  },
  {
    id: 'gb-ads',
    titleAr: 'إدارة الحملة الإعلانية',
    titleEn: 'Ads Management',
    summaryAr: 'حملات إعلانية مدفوعة وموجهة.',
    summaryEn: 'Paid and targeted advertising campaigns.',
    accent: ACCENTS.amber,
    icon: 'Target',
    href: '/social?planType=advertising#advertising-plans-row',
    group: 'growth'
  },
  {
    id: 'gb-design',
    titleAr: 'تصميم',
    titleEn: 'Design',
    summaryAr: 'تصميم الهوية البصرية للشركات.',
    summaryEn: 'Corporate brand identity design.',
    accent: ACCENTS.magenta,
    icon: 'Palette',
    href: '/branding?addon=identity#plan-builder',
    group: 'growth'
  },

  // MEDIA
  {
    id: 'md-product',
    titleAr: 'تصوير المنتجات الاحترافي',
    titleEn: 'Product Photography',
    summaryAr: 'إبراز تفاصيل المنتجات بأعلى جودة.',
    summaryEn: 'Highlighting product details with highest quality.',
    accent: ACCENTS.rose,
    icon: 'Camera',
    href: '/media#service-card-product-photo',
    group: 'media'
  },
  {
    id: 'md-portrait',
    titleAr: 'بورتريه وصور شخصية',
    titleEn: 'Corporate Portraits',
    summaryAr: 'صور احترافية لفريق العمل.',
    summaryEn: 'Professional headshots for the team.',
    accent: ACCENTS.rose,
    icon: 'User',
    href: '/media#service-card-portrait-headshots',
    group: 'media'
  },
  {
    id: 'md-drone',
    titleAr: 'تصوير جوي بالدرون',
    titleEn: 'Drone Photography',
    summaryAr: 'لقطات جوية للمشاريع والمنشآت.',
    summaryEn: 'Aerial shots for projects and facilities.',
    accent: ACCENTS.rose,
    icon: 'Plane',
    href: '/media#service-card-drone-aerial',
    group: 'media'
  },
  {
    id: 'md-motion',
    titleAr: 'موشن جرافيك وأنيميشن',
    titleEn: 'Motion Graphics',
    summaryAr: 'تحريك الرسومات بشكل إبداعي.',
    summaryEn: 'Creative animation of graphics.',
    accent: ACCENTS.rose,
    icon: 'Film',
    href: '/media#service-card-motion-graphics',
    group: 'media'
  },
  {
    id: 'md-commercial',
    titleAr: 'إنتاج الفيديو الإعلاني',
    titleEn: 'Commercial Video',
    summaryAr: 'إعلانات مرئية متكاملة الإنتاج.',
    summaryEn: 'Fully produced visual commercials.',
    accent: ACCENTS.rose,
    icon: 'Video',
    href: '/media#service-card-commercial-video',
    group: 'media'
  }
];

export const portfolioTeamNodes: PortfolioTeamNode[] = [
  createNode({
    id: 'kareem-saber',
    ring: 0,
    order: 0,
    nameAr: 'كريم صابر',
    nameEn: 'Kareem Saber',
    titleAr: 'CEO',
    titleEn: 'CEO',
    bioAr:
      'يقود القرار التنفيذي ويضبط اتجاه المنظومة بالكامل بين الجودة، السرعة، ونطاق التنفيذ التجاري.',
    bioEn:
      'Sets executive direction and keeps the whole delivery system aligned across quality, pace, and commercial scope.',
    departmentAr: 'الإدارة التنفيذية',
    departmentEn: 'Executive Office',
    accent: ACCENTS.ink,
    projectTags: ['Brand strategy', 'Commercial direction'],
  }),
  createNode({
    id: 'amira-hassan',
    ring: 1,
    order: 0,
    nameAr: 'أميرة حسن',
    nameEn: 'Amira Hassan',
    titleAr: 'Chief Strategy Officer',
    titleEn: 'Chief Strategy Officer',
    bioAr: 'تحول أهداف العملاء إلى خارطة قرار قابلة للتنفيذ عبر كل الدوائر.',
    bioEn: 'Translates client goals into an execution-ready decision map across every ring.',
    departmentAr: 'الاستراتيجية',
    departmentEn: 'Strategy',
    accent: ACCENTS.magenta,
    projectTags: ['Brand systems', 'Growth mapping'],
  }),
  createNode({
    id: 'mohamed-adel',
    ring: 1,
    order: 1,
    nameAr: 'محمد عادل',
    nameEn: 'Mohamed Adel',
    titleAr: 'Chief Operations Officer',
    titleEn: 'Chief Operations Officer',
    bioAr: 'يضبط الإيقاع التشغيلي بين الفرق والتسليمات والجودة اليومية.',
    bioEn: 'Owns the operating rhythm across teams, delivery timing, and daily quality.',
    departmentAr: 'العمليات',
    departmentEn: 'Operations',
    accent: ACCENTS.plum,
    projectTags: ['Delivery oversight', 'Operations flow'],
  }),
  createNode({
    id: 'salma-youssef',
    ring: 1,
    order: 2,
    nameAr: 'سلمى يوسف',
    nameEn: 'Salma Youssef',
    titleAr: 'Creative Director',
    titleEn: 'Creative Director',
    bioAr: 'تربط بين الهوية والمحتوى والمشهد النهائي بحيث يخرج العمل بصوت واحد.',
    bioEn: 'Brings identity, content, and the final visual output into one coherent voice.',
    departmentAr: 'الإبداع',
    departmentEn: 'Creative',
    accent: ACCENTS.rose,
    projectTags: ['Identity direction', 'Creative reviews'],
  }),
  createNode({
    id: 'omar-fathy',
    ring: 1,
    order: 3,
    nameAr: 'عمر فتحي',
    nameEn: 'Omar Fathy',
    titleAr: 'Technical Director',
    titleEn: 'Technical Director',
    bioAr: 'يشرف على القرارات التقنية وبنية المنصات وربطها بالتسويق والعمليات.',
    bioEn: 'Owns technical decisions, platform architecture, and delivery links across growth and ops.',
    departmentAr: 'التقنية',
    departmentEn: 'Technology',
    accent: ACCENTS.slate,
    projectTags: ['Platform architecture', 'Integrations'],
  }),
  createNode({
    id: 'nouran-sami',
    ring: 1,
    order: 4,
    nameAr: 'نوران سامي',
    nameEn: 'Nouran Sami',
    titleAr: 'Growth Director',
    titleEn: 'Growth Director',
    bioAr: 'تدير مسارات النمو وتوزيع الأولويات بين المحتوى والأداء والقياس.',
    bioEn: 'Leads growth priorities across content, performance, and measurement.',
    departmentAr: 'النمو',
    departmentEn: 'Growth',
    accent: ACCENTS.gold,
    projectTags: ['Performance oversight', 'Acquisition strategy'],
  }),
  createNode({
    id: 'yara-mostafa',
    ring: 1,
    order: 5,
    nameAr: 'يارا مصطفى',
    nameEn: 'Yara Mostafa',
    titleAr: 'Client Success Director',
    titleEn: 'Client Success Director',
    bioAr: 'تحافظ على وضوح التواصل مع العملاء وتربط التوقعات بالواقع التنفيذي.',
    bioEn: 'Keeps client communication crisp and aligns expectations with actual delivery.',
    departmentAr: 'نجاح العملاء',
    departmentEn: 'Client Success',
    accent: ACCENTS.amber,
    projectTags: ['Client communication', 'Account health'],
  }),
  createNode({
    id: 'layla-hamdy',
    ring: 2,
    order: 0,
    nameAr: 'ليلى حمدي',
    nameEn: 'Layla Hamdy',
    titleAr: 'Brand Strategy Lead',
    titleEn: 'Brand Strategy Lead',
    bioAr: 'تترجم رؤية البراند إلى لغة بصرية يمكن استخدامها يوميًا بثبات.',
    bioEn: 'Turns brand direction into an everyday visual system with consistent use.',
    departmentAr: 'الهوية',
    departmentEn: 'Brand',
    accent: ACCENTS.magenta,
    projectTags: ['Identity systems', 'Brand manuals'],
  }),
  createNode({
    id: 'ahmed-shawky',
    ring: 2,
    order: 1,
    nameAr: 'أحمد شوقي',
    nameEn: 'Ahmed Shawky',
    titleAr: 'Web Experience Lead',
    titleEn: 'Web Experience Lead',
    bioAr: 'يقود تجربة المواقع من أول تدفق حتى التسليم واختبار الاستخدام.',
    bioEn: 'Leads website experience from initial flows through launch and usability review.',
    departmentAr: 'المواقع',
    departmentEn: 'Web',
    accent: ACCENTS.gold,
    projectTags: ['UX architecture', 'Launch readiness'],
  }),
  createNode({
    id: 'dina-gaber',
    ring: 2,
    order: 2,
    nameAr: 'دينا جابر',
    nameEn: 'Dina Gaber',
    titleAr: 'Social Media Lead',
    titleEn: 'Social Media Lead',
    bioAr: 'تضبط إيقاع النشر والتقويم والمخرجات اليومية للحملات والحضور.',
    bioEn: 'Owns publishing cadence, editorial calendars, and daily campaign output.',
    departmentAr: 'السوشيال',
    departmentEn: 'Social',
    accent: ACCENTS.amber,
    projectTags: ['Campaign content', 'Social systems'],
  }),
  createNode({
    id: 'karim-shehata',
    ring: 2,
    order: 3,
    nameAr: 'كريم شحاتة',
    nameEn: 'Karim Shehata',
    titleAr: 'Motion Director',
    titleEn: 'Motion Director',
    bioAr: 'يحرك الرسالة بصريًا بين الشرح والإيقاع والإخراج السلس.',
    bioEn: 'Shapes the motion layer from explainers to polished visual rhythm.',
    departmentAr: 'الموشن',
    departmentEn: 'Motion',
    accent: ACCENTS.rose,
    projectTags: ['Explainers', 'Motion systems'],
  }),
  createNode({
    id: 'mariem-khaled',
    ring: 2,
    order: 4,
    nameAr: 'مريم خالد',
    nameEn: 'Mariem Khaled',
    titleAr: 'Media Production Lead',
    titleEn: 'Media Production Lead',
    bioAr: 'تدير خط الإنتاج المصور بين التحضير والجدولة وجودة الخروج النهائي.',
    bioEn: 'Runs filmed production from prep and scheduling through final output quality.',
    departmentAr: 'الإنتاج',
    departmentEn: 'Production',
    accent: ACCENTS.plum,
    projectTags: ['Shoot planning', 'Production logistics'],
  }),
  createNode({
    id: 'farah-saad',
    ring: 2,
    order: 5,
    nameAr: 'فرح سعد',
    nameEn: 'Farah Saad',
    titleAr: 'Product Photography Lead',
    titleEn: 'Product Photography Lead',
    bioAr: 'تقود خط التصوير وتوحيد النظرة البصرية للمنتجات والمشاهد.',
    bioEn: 'Leads the photography lane and the visual consistency of products and sets.',
    departmentAr: 'التصوير',
    departmentEn: 'Photography',
    accent: ACCENTS.teal,
    projectTags: ['Studio capture', 'Visual polish'],
  }),
  createNode({
    id: 'tarek-hassan',
    ring: 2,
    order: 6,
    nameAr: 'طارق حسن',
    nameEn: 'Tarek Hassan',
    titleAr: 'Software Delivery Lead',
    titleEn: 'Software Delivery Lead',
    bioAr: 'يربط بناء البرمجيات بالاحتياج العملي ويحول الطلبات إلى roadmap واضحة.',
    bioEn: 'Connects software delivery to practical business needs and keeps the roadmap clear.',
    departmentAr: 'البرمجيات',
    departmentEn: 'Software',
    accent: ACCENTS.slate,
    projectTags: ['Software delivery', 'Backlog ownership'],
  }),
  createNode({
    id: 'rana-hafez',
    ring: 2,
    order: 7,
    nameAr: 'رنا حافظ',
    nameEn: 'Rana Hafez',
    titleAr: 'Performance Marketing Lead',
    titleEn: 'Performance Marketing Lead',
    bioAr: 'تراقب الميزانيات، الرسائل، ومواطن التحسين السريع عبر القنوات.',
    bioEn: 'Owns budgets, messaging performance, and rapid optimization loops across channels.',
    departmentAr: 'الأداء',
    departmentEn: 'Performance',
    accent: ACCENTS.gold,
    projectTags: ['Media buying', 'ROAS tracking'],
  }),
  createNode({
    id: 'hisham-magdy',
    ring: 2,
    order: 8,
    nameAr: 'هشام مجدي',
    nameEn: 'Hisham Magdy',
    titleAr: 'Sales Operations Lead',
    titleEn: 'Sales Operations Lead',
    bioAr: 'يضبط نقطة تسليم العميل من الاهتمام إلى المحادثة والتحويل التجاري.',
    bioEn: 'Keeps the handoff from qualified interest to live commercial follow-up tightly aligned.',
    departmentAr: 'المبيعات',
    departmentEn: 'Sales Ops',
    accent: ACCENTS.amber,
    projectTags: ['Lead routing', 'Sales enablement'],
  }),
  createNode({
    id: 'asmaa-fouad',
    ring: 2,
    order: 9,
    nameAr: 'أسماء فؤاد',
    nameEn: 'Asmaa Fouad',
    titleAr: 'People & Culture Lead',
    titleEn: 'People & Culture Lead',
    bioAr: 'تحافظ على اتساق الفريق الداخلي وتدفق المعرفة بين المسارات.',
    bioEn: 'Supports team consistency and knowledge flow between delivery tracks.',
    departmentAr: 'الموارد البشرية',
    departmentEn: 'People & Culture',
    accent: ACCENTS.teal,
    projectTags: ['Team alignment', 'Internal enablement'],
  }),
  createNode({
    id: 'sara-tarek',
    ring: 3,
    order: 0,
    nameAr: 'سارة طارق',
    nameEn: 'Sara Tarek',
    titleAr: 'Senior Brand Designer',
    titleEn: 'Senior Brand Designer',
    bioAr: 'تطوّر عناصر الهوية الرئيسية وتراجع انسجامها في التطبيق.',
    bioEn: 'Develops core brand assets and reviews their consistency in application.',
    departmentAr: 'الهوية',
    departmentEn: 'Brand',
    accent: ACCENTS.magenta,
    projectTags: ['Logo systems', 'Brand assets'],
  }),
  createNode({
    id: 'youssef-badr',
    ring: 3,
    order: 1,
    nameAr: 'يوسف بدر',
    nameEn: 'Youssef Badr',
    titleAr: 'Visual Identity Designer',
    titleEn: 'Visual Identity Designer',
    bioAr: 'يبني الشبكات البصرية والمواد المساندة للهوية الأساسية.',
    bioEn: 'Builds the secondary visual grid and support assets around the core identity.',
    departmentAr: 'الهوية',
    departmentEn: 'Brand',
    accent: ACCENTS.rose,
    projectTags: ['Identity layouts', 'Application systems'],
  }),
  createNode({
    id: 'nada-shaker',
    ring: 3,
    order: 2,
    nameAr: 'ندى شاكر',
    nameEn: 'Nada Shaker',
    titleAr: 'UI/UX Designer',
    titleEn: 'UI/UX Designer',
    bioAr: 'تصوغ الواجهات وتدفقات الاستخدام بما يخدم القرار التجاري.',
    bioEn: 'Shapes interfaces and flows around business-ready user decisions.',
    departmentAr: 'المواقع',
    departmentEn: 'Web',
    accent: ACCENTS.gold,
    projectTags: ['Wireframes', 'Interface systems'],
  }),
  createNode({
    id: 'adel-hesham',
    ring: 3,
    order: 3,
    nameAr: 'عادل هشام',
    nameEn: 'Adel Hesham',
    titleAr: 'Frontend Engineer',
    titleEn: 'Frontend Engineer',
    bioAr: 'يحافظ على جودة التنفيذ البصري وسرعة التفاعل عبر الواجهات.',
    bioEn: 'Owns visual implementation quality and interaction speed across interfaces.',
    departmentAr: 'البرمجة',
    departmentEn: 'Engineering',
    accent: ACCENTS.slate,
    projectTags: ['Frontend delivery', 'Interaction polish'],
  }),
  createNode({
    id: 'basma-sherif',
    ring: 3,
    order: 4,
    nameAr: 'بسمة شريف',
    nameEn: 'Basma Sherif',
    titleAr: 'Backend Engineer',
    titleEn: 'Backend Engineer',
    bioAr: 'تبني الخدمات الخلفية وتربط البيانات بمخرجات الاستخدام اليومية.',
    bioEn: 'Builds backend services and ties data flows into everyday product behavior.',
    departmentAr: 'البرمجة',
    departmentEn: 'Engineering',
    accent: ACCENTS.slate,
    projectTags: ['Backend systems', 'Data services'],
  }),
  createNode({
    id: 'ibrahim-maher',
    ring: 3,
    order: 5,
    nameAr: 'إبراهيم ماهر',
    nameEn: 'Ibrahim Maher',
    titleAr: 'Automation Engineer',
    titleEn: 'Automation Engineer',
    bioAr: 'يبني الاختصارات والأتمتة التي تقلل الزمن بين الطلب والتنفيذ.',
    bioEn: 'Builds automations that shorten the path between request and delivery.',
    departmentAr: 'الأتمتة',
    departmentEn: 'Automation',
    accent: ACCENTS.teal,
    projectTags: ['Automation', 'Internal tooling'],
  }),
  createNode({
    id: 'habiba-nasser',
    ring: 3,
    order: 6,
    nameAr: 'حبيبة ناصر',
    nameEn: 'Habiba Nasser',
    titleAr: 'Content Strategist',
    titleEn: 'Content Strategist',
    bioAr: 'تحدد زاوية الرسالة وخطة المحتوى بما يخدم كل مسار من مسارات النمو.',
    bioEn: 'Owns messaging angles and content structure for the different growth tracks.',
    departmentAr: 'المحتوى',
    departmentEn: 'Content',
    accent: ACCENTS.amber,
    projectTags: ['Content systems', 'Editorial direction'],
  }),
  createNode({
    id: 'mostafa-ayman',
    ring: 3,
    order: 7,
    nameAr: 'مصطفى أيمن',
    nameEn: 'Mostafa Ayman',
    titleAr: 'Arabic Copywriter',
    titleEn: 'Arabic Copywriter',
    bioAr: 'يصيغ النص التجاري بصوت واضح ومقنع يليق بمكانة البراند.',
    bioEn: 'Writes persuasive Arabic commercial copy with clarity and brand weight.',
    departmentAr: 'المحتوى',
    departmentEn: 'Content',
    accent: ACCENTS.rose,
    projectTags: ['Copy systems', 'Campaign lines'],
  }),
  createNode({
    id: 'malak-reda',
    ring: 3,
    order: 8,
    nameAr: 'ملك رضا',
    nameEn: 'Malak Reda',
    titleAr: 'Media Buyer',
    titleEn: 'Media Buyer',
    bioAr: 'تحرك الحملات يوميًا وتختبر الفرضيات بسرعة على أرض الواقع.',
    bioEn: 'Runs live media tests and daily optimizations against real performance signals.',
    departmentAr: 'الأداء',
    departmentEn: 'Performance',
    accent: ACCENTS.gold,
    projectTags: ['Paid media', 'Optimization loops'],
  }),
  createNode({
    id: 'waleed-farouk',
    ring: 3,
    order: 9,
    nameAr: 'وليد فاروق',
    nameEn: 'Waleed Farouk',
    titleAr: 'Community Manager',
    titleEn: 'Community Manager',
    bioAr: 'يمسك بنبض التفاعل اليومي ويربط ردود الجمهور بخطة المحتوى.',
    bioEn: 'Keeps the community pulse visible and feeds audience reactions back into content.',
    departmentAr: 'السوشيال',
    departmentEn: 'Social',
    accent: ACCENTS.amber,
    projectTags: ['Community care', 'Engagement tracking'],
  }),
  createNode({
    id: 'lina-fekry',
    ring: 3,
    order: 10,
    nameAr: 'لينا فكري',
    nameEn: 'Lina Fekry',
    titleAr: 'Motion Designer',
    titleEn: 'Motion Designer',
    bioAr: 'تحول اللقطات الثابتة إلى إيقاع بصري واضح ومشوق.',
    bioEn: 'Turns static frames into motion with clear rhythm and visual pull.',
    departmentAr: 'الموشن',
    departmentEn: 'Motion',
    accent: ACCENTS.rose,
    projectTags: ['Motion frames', 'Animated explainers'],
  }),
  createNode({
    id: 'hazem-atef',
    ring: 3,
    order: 11,
    nameAr: 'حازم عاطف',
    nameEn: 'Hazem Atef',
    titleAr: 'Video Editor',
    titleEn: 'Video Editor',
    bioAr: 'يضبط سرد الفيديو والإيقاع والانتقالات النهائية للمشهد.',
    bioEn: 'Owns pacing, cut structure, and final transitions inside the film layer.',
    departmentAr: 'الإنتاج',
    departmentEn: 'Production',
    accent: ACCENTS.plum,
    projectTags: ['Edits', 'Delivery masters'],
  }),
  createNode({
    id: 'jana-emad',
    ring: 3,
    order: 12,
    nameAr: 'جنى عماد',
    nameEn: 'Jana Emad',
    titleAr: 'Studio Producer',
    titleEn: 'Studio Producer',
    bioAr: 'تنظم تفاصيل الجلسات والجدولة والانتقال السلس بين فرق التصوير.',
    bioEn: 'Coordinates studio sessions, schedules, and the handoff between capture teams.',
    departmentAr: 'الإنتاج',
    departmentEn: 'Production',
    accent: ACCENTS.teal,
    projectTags: ['Studio logistics', 'Production support'],
  }),
  createNode({
    id: 'amr-saeed',
    ring: 3,
    order: 13,
    nameAr: 'عمرو سعيد',
    nameEn: 'Amr Saeed',
    titleAr: 'Product Photographer',
    titleEn: 'Product Photographer',
    bioAr: 'يخرج المنتج من كونه عنصرًا معروضًا إلى مشهد بيع واضح.',
    bioEn: 'Turns products from static items into sharp visual sales scenes.',
    departmentAr: 'التصوير',
    departmentEn: 'Photography',
    accent: ACCENTS.teal,
    projectTags: ['Product stills', 'Studio lighting'],
  }),
  createNode({
    id: 'reem-ashraf',
    ring: 3,
    order: 14,
    nameAr: 'ريم أشرف',
    nameEn: 'Reem Ashraf',
    titleAr: 'CRM Specialist',
    titleEn: 'CRM Specialist',
    bioAr: 'تربط التفاعل القادم من الحملات بمسارات المتابعة والاحتفاظ.',
    bioEn: 'Connects inbound demand to CRM workflows, follow-up, and retention.',
    departmentAr: 'العمليات',
    departmentEn: 'Operations',
    accent: ACCENTS.plum,
    projectTags: ['CRM flows', 'Lead lifecycle'],
  }),
  createNode({
    id: 'samih-mansour',
    ring: 3,
    order: 15,
    nameAr: 'سميح منصور',
    nameEn: 'Samih Mansour',
    titleAr: 'Data Analyst',
    titleEn: 'Data Analyst',
    bioAr: 'يحول الإشارات الرقمية إلى قرارات عملية قابلة للتنفيذ بسرعة.',
    bioEn: 'Turns data signals into practical operating decisions that teams can act on fast.',
    departmentAr: 'القياس',
    departmentEn: 'Analytics',
    accent: ACCENTS.gold,
    projectTags: ['Reporting', 'Decision support'],
  }),
  createNode({
    id: 'nour-habib',
    ring: 3,
    order: 16,
    nameAr: 'نور حبيب',
    nameEn: 'Nour Habib',
    titleAr: 'Partnerships Executive',
    titleEn: 'Partnerships Executive',
    bioAr: 'تفتح مسارات التعاون وتربط المنظومة بفرص التوسع الخارجي.',
    bioEn: 'Builds partnership lanes and keeps external expansion opportunities in motion.',
    departmentAr: 'الشراكات',
    departmentEn: 'Partnerships',
    accent: ACCENTS.amber,
    projectTags: ['Partnerships', 'External growth'],
  }),
  createNode({
    id: 'shahd-kamal',
    ring: 3,
    order: 17,
    nameAr: 'شهد كمال',
    nameEn: 'Shahd Kamal',
    titleAr: 'Customer Success Specialist',
    titleEn: 'Customer Success Specialist',
    bioAr: 'تحافظ على وضوح الحالة اليومية للحسابات وتمنع التشتت بين المسارات.',
    bioEn: 'Keeps account status clear day to day and prevents drift between delivery lanes.',
    departmentAr: 'نجاح العملاء',
    departmentEn: 'Client Success',
    accent: ACCENTS.magenta,
    projectTags: ['Accounts', 'Client rhythm'],
  }),
];
